services:
  - type: web
    name: texas-tailgaters
    env: static
    # Force clean build - updated Sep 14 2025 2:00 AM
    buildCommand: rm -rf node_modules dist && npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20